.TH "Product" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Product \- Базовый класс, представляющий товар  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBookProduct\fP, and \fBElectronicProduct\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProduct\fP (int \fBid\fP, const string &\fBname\fP, double \fBprice\fP)"
.br
.RI "Создает новый экземпляр класса \fBProduct\fP\&. "
.ti -1c
.RI "virtual void \fBdisplayInfo\fP () const"
.br
.RI "Выводит информацию о товаре "
.ti -1c
.RI "string \fBgetInfo\fP () const"
.br
.RI "Возвращает информацию о товаре в виде строки "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "Идентификатор товара "
.ti -1c
.RI "string \fBname\fP"
.br
.RI "Название товара "
.ti -1c
.RI "double \fBprice\fP"
.br
.RI "Цена товара "
.in -1c
.SH "Detailed Description"
.PP 
Базовый класс, представляющий товар 


.IP "\(bu" 2
  \[
x_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}
\] 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Product::Product (int id, const string & name, double price)\fR [inline]\fP"

.PP
Создает новый экземпляр класса \fBProduct\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP Идентификатор товара 
.br
\fIname\fP Название товара 
.br
\fIprice\fP Цена товара 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual void Product::displayInfo () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Выводит информацию о товаре 
.PP
Reimplemented in \fBElectronicProduct\fP, and \fBBookProduct\fP\&.
.SS "string Product::getInfo () const\fR [inline]\fP"

.PP
Возвращает информацию о товаре в виде строки 
.PP
\fBReturns\fP
.RS 4
Строка с информацией о товаре 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
